'use client';

import React, { useState, useEffect } from 'react';
import { cockpit3dProducts } from '@/data/cockpit3d-products';
import { Product, ProductCustomizations, ProductImage } from '@/types/productTypes';
import ProductGallery2 from '@/components/ProductGallery2';
import ImageUpload from '@/components/admin/ImageUpload';

export default function ProductAdminPage() {
  const [sourceProducts] = useState<Product[]>(cockpit3dProducts as Product[]);
  const [editedProducts, setEditedProducts] = useState<ProductCustomizations>({});
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [showPreview, setShowPreview] = useState(false);

  // Load existing customizations from localStorage
  useEffect(() => {
    try {
      const saved = localStorage.getItem('productCustomizations');
      if (saved) {
        setEditedProducts(JSON.parse(saved));
      }
    } catch (e) {
      console.warn('No existing customizations found');
    }
  }, []);

  // Get merged product data (source + customizations)
  const getProductData = (productId: string): Product => {
    const sourceProduct = sourceProducts.find((p) => p.id === productId);
    const customizations = editedProducts[productId] || {};
    return { ...sourceProduct, ...customizations } as Product;
  };

  // Update product customization
  const updateProduct = (productId: string, updates: Partial<Product>) => {
    setEditedProducts((prev) => ({
      ...prev,
      [productId]: { ...prev[productId], ...updates },
    }));
  };

  // Handle images update
  const handleImagesUpdated = (productId: string, updatedImages: ProductImage[]) => {
    updateProduct(productId, { images: updatedImages });
  };

  // Generate final product list
  const generateFinalProducts = () => {
    const finalProducts = sourceProducts.map((product) => {
      const customizations = editedProducts[product.id] || {};
      return { ...product, ...customizations };
    });

    const content = `// final-product-list.js - Generated by Admin Panel
// DO NOT EDIT MANUALLY - Generated from cockpit3d-products.js + customizations
// Generated: ${new Date().toISOString()}

export const finalProductList = ${JSON.stringify(finalProducts, null, 2)};

export const customizationInfo = {
  generated_at: "${new Date().toISOString()}",
  source_products: ${sourceProducts.length},
  customized_products: ${Object.keys(editedProducts).length},
  total_products: ${finalProducts.length},
  has_custom_images: ${finalProducts.some((p) => p.images?.length > 1)},
  admin_customized: true
};

export default finalProductList;
`;

    return content;
  };

  // Save and download final product list
  const saveFinalProducts = () => {
    const content = generateFinalProducts();
    const blob = new Blob([content], { type: 'application/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'final-product-list.js';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    // Also save to localStorage
    localStorage.setItem('productCustomizations', JSON.stringify(editedProducts));

    alert('final-product-list.js generated! Replace the file in your src/data/ folder.');
  };

  const hasCustomizations = (productId: string) => {
    return editedProducts[productId] && Object.keys(editedProducts[productId]).length > 0;
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white shadow-sm border-b sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 py-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Product Admin Panel</h1>
              <p className="text-sm text-gray-600 mt-1">
                Manage products, images, descriptions, and pricing
              </p>
            </div>
            <div className="flex gap-3">
              <button
                onClick={() => setShowPreview(!showPreview)}
                className={`px-4 py-2 rounded-lg font-medium transition-colors ${
                  showPreview
                    ? 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                    : 'bg-blue-600 text-white hover:bg-blue-700'
                }`}
              >
                {showPreview ? '👁️ Hide Preview' : '👁️ Show Preview'}
              </button>
              <button
                onClick={saveFinalProducts}
                className="px-4 py-2 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 transition-colors"
              >
                💾 Generate final-product-list.js
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-4 py-6 sm:px-6 lg:px-8">
        <div className="grid grid-cols-12 gap-6">
          {/* Product List - Left Column */}
          <div className="col-span-12 lg:col-span-4">
            <div className="bg-white rounded-lg shadow-sm border">
              <div className="p-4 border-b bg-gray-50">
                <h2 className="text-lg font-semibold text-gray-900">
                  Products ({sourceProducts.length})
                </h2>
                <p className="text-sm text-gray-600">Select a product to edit</p>
              </div>
              <div className="overflow-y-auto" style={{ maxHeight: '70vh' }}>
                {sourceProducts.map((product) => (
                  <button
                    key={product.id}
                    onClick={() => setSelectedProduct(product)}
                    className={`w-full text-left p-4 border-b hover:bg-gray-50 transition-colors ${
                      selectedProduct?.id === product.id ? 'bg-blue-50 border-l-4 border-l-blue-600' : ''
                    }`}
                  >
                    <div className="flex items-start gap-3">
                      {/* Product Thumbnail */}
                      <div className="w-16 h-16 flex-shrink-0 bg-gray-100 rounded overflow-hidden">
                        {product.images && product.images.length > 0 ? (
                          <img
                            src={product.images[0].src}
                            alt={product.name}
                            className="w-full h-full object-cover"
                          />
                        ) : (
                          <div className="w-full h-full flex items-center justify-center text-gray-400 text-xs">
                            No image
                          </div>
                        )}
                      </div>

                      {/* Product Info */}
                      <div className="flex-1 min-w-0">
                        <h3 className="font-semibold text-gray-900 truncate">{product.name}</h3>
                        <p className="text-sm text-gray-600">ID: {product.id} • SKU: {product.sku}</p>
                        <p className="text-green-600 font-bold mt-1">${product.basePrice}</p>
                        {hasCustomizations(product.id) && (
                          <span className="inline-block mt-1 px-2 py-0.5 bg-green-100 text-green-800 text-xs font-medium rounded">
                            Modified
                          </span>
                        )}
                      </div>
                    </div>
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Edit Panel - Middle Column */}
          <div className="col-span-12 lg:col-span-4">
            <div className="bg-white rounded-lg shadow-sm border">
              <div className="p-4 border-b bg-gray-50">
                <h2 className="text-lg font-semibold text-gray-900">
                  {selectedProduct ? `Edit: ${selectedProduct.name}` : 'Select a Product'}
                </h2>
              </div>
              <div className="p-6 overflow-y-auto" style={{ maxHeight: '70vh' }}>
                {selectedProduct ? (
                  <div className="space-y-6">
                    {/* Basic Info */}
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Display Name
                      </label>
                      <input
                        type="text"
                        value={getProductData(selectedProduct.id).name}
                        onChange={(e) => updateProduct(selectedProduct.id, { name: e.target.value })}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Short Description
                      </label>
                      <input
                        type="text"
                        value={getProductData(selectedProduct.id).description || ''}
                        onChange={(e) => updateProduct(selectedProduct.id, { description: e.target.value })}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Long Description
                      </label>
                      <textarea
                        rows={4}
                        value={getProductData(selectedProduct.id).longDescription || ''}
                        onChange={(e) =>
                          updateProduct(selectedProduct.id, { longDescription: e.target.value })
                        }
                        placeholder="Detailed product description..."
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Base Price Override
                      </label>
                      <input
                        type="number"
                        step="0.01"
                        value={getProductData(selectedProduct.id).basePrice}
                        onChange={(e) =>
                          updateProduct(selectedProduct.id, { basePrice: parseFloat(e.target.value) })
                        }
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                      />
                    </div>

                    <div>
                      <label className="flex items-center space-x-2">
                        <input
                          type="checkbox"
                          checked={getProductData(selectedProduct.id).featured || false}
                          onChange={(e) => updateProduct(selectedProduct.id, { featured: e.target.checked })}
                          className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                        />
                        <span className="text-sm font-medium text-gray-700">Show as featured product</span>
                      </label>
                    </div>

                    {/* Product Images Section */}
                    <div className="border-t pt-6">
                      <h3 className="text-lg font-semibold text-gray-900 mb-4">📸 Product Images</h3>
                      <ImageUpload
                        productId={selectedProduct.id}
                        images={getProductData(selectedProduct.id).images || []}
                        onImagesUpdated={(images) => handleImagesUpdated(selectedProduct.id, images)}
                      />
                    </div>

                    {/* Reset Button */}
                    <div className="border-t pt-6">
                      <button
                        onClick={() => {
                          const newEditedProducts = { ...editedProducts };
                          delete newEditedProducts[selectedProduct.id];
                          setEditedProducts(newEditedProducts);
                        }}
                        className="w-full px-4 py-2 bg-red-50 text-red-600 rounded-lg font-medium hover:bg-red-100 transition-colors"
                      >
                        Reset to Original
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="text-center py-12">
                    <p className="text-gray-500">Select a product from the list to edit</p>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Preview Panel - Right Column */}
          {showPreview && (
            <div className="col-span-12 lg:col-span-4">
              <div className="bg-white rounded-lg shadow-sm border">
                <div className="p-4 border-b bg-gray-50">
                  <h2 className="text-lg font-semibold text-gray-900">Preview</h2>
                </div>
                <div className="p-6 overflow-y-auto" style={{ maxHeight: '70vh' }}>
                  {selectedProduct ? (
                    <div className="space-y-4">
                      {/* Gallery Preview */}
                      <div>
                        <h3 className="text-sm font-semibold text-gray-700 mb-2">Image Gallery</h3>
                        <ProductGallery2
                          images={getProductData(selectedProduct.id).images || []}
                          productName={getProductData(selectedProduct.id).name}
                        />
                      </div>

                      {/* Product Details Preview */}
                      <div className="border-t pt-4">
                        <h3 className="text-2xl font-bold text-gray-900 mb-2">
                          {getProductData(selectedProduct.id).name}
                        </h3>
                        <p className="text-3xl font-bold text-green-600 mb-4">
                          ${getProductData(selectedProduct.id).basePrice}
                        </p>
                        <p className="text-gray-700 mb-4">
                          {getProductData(selectedProduct.id).description}
                        </p>
                        {getProductData(selectedProduct.id).longDescription && (
                          <div className="text-sm text-gray-600 bg-gray-50 p-4 rounded-lg">
                            <p className="font-semibold mb-2">Detailed Description:</p>
                            <p>{getProductData(selectedProduct.id).longDescription}</p>
                          </div>
                        )}
                      </div>
                    </div>
                  ) : (
                    <div className="text-center py-12">
                      <p className="text-gray-500">Select a product to see preview</p>
                    </div>
                  )}
                </div>
              </div>

              {/* Stats */}
              <div className="mt-6 grid grid-cols-3 gap-3">
                <div className="bg-blue-50 rounded-lg p-4 text-center">
                  <div className="text-sm font-medium text-blue-600">Source</div>
                  <div className="text-2xl font-bold text-blue-900">{sourceProducts.length}</div>
                </div>
                <div className="bg-green-50 rounded-lg p-4 text-center">
                  <div className="text-sm font-medium text-green-600">Customized</div>
                  <div className="text-2xl font-bold text-green-900">
                    {Object.keys(editedProducts).length}
                  </div>
                </div>
                <div className="bg-purple-50 rounded-lg p-4 text-center">
                  <div className="text-sm font-medium text-purple-600">Total</div>
                  <div className="text-2xl font-bold text-purple-900">{sourceProducts.length}</div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
