'use client';

import React, { useState, useEffect } from 'react';
import { finalProductList as cockpit3dProducts } from '@/data/final-product-list';
import { Product, ProductCustomizations, ProductImage } from '@/types/productTypes';
import ImageUpload from '@/components/admin/ImageUpload';

export default function ProductAdminPage() {
  const [sourceProducts] = useState<Product[]>(cockpit3dProducts as Product[]);
  const [editedProducts, setEditedProducts] = useState<ProductCustomizations>({});
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [showPreview, setShowPreview] = useState(false);

  // Load customizations on mount
  useEffect(() => {
    try {
      const saved = localStorage.getItem('productCustomizations');
      if (saved) {
        setEditedProducts(JSON.parse(saved));
      }
    } catch (e) {
      console.warn('No existing customizations found');
    }
  }, []);

  // Auto-save customizations whenever they change
  useEffect(() => {
    if (Object.keys(editedProducts).length > 0) {
      localStorage.setItem('productCustomizations', JSON.stringify(editedProducts));
    }
  }, [editedProducts]);

  const getProductData = (productId: string): Product => {
    const sourceProduct = sourceProducts.find((p) => p.id === productId);
    const customizations = editedProducts[productId] || {};
    return { ...sourceProduct, ...customizations } as Product;
  };

  const updateProduct = (productId: string, updates: Partial<Product>) => {
    setEditedProducts((prev) => ({
      ...prev,
      [productId]: { ...prev[productId], ...updates },
    }));
  };

  const handleImagesUpdated = (productId: string, updatedImages: ProductImage[]) => {
    updateProduct(productId, { images: updatedImages });
  };

  const generateFinalProducts = () => {
    const finalProducts = sourceProducts.map((product) => {
      const customizations = editedProducts[product.id] || {};
      return { ...product, ...customizations };
    });

    return `// final-product-list.js - Generated by Admin Panel
// DO NOT EDIT MANUALLY
// Generated: ${new Date().toISOString()}

export const finalProductList = ${JSON.stringify(finalProducts, null, 2)};

export const customizationInfo = {
  generated_at: "${new Date().toISOString()}",
  source_products: ${sourceProducts.length},
  customized_products: ${Object.keys(editedProducts).length},
  total_products: ${finalProducts.length},
  has_custom_images: ${finalProducts.some((p) => p.images?.length > 1)},
  admin_customized: true
};

export default finalProductList;
`;
  };

  const saveFinalProducts = () => {
    const content = generateFinalProducts();
    const blob = new Blob([content], { type: 'application/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'final-product-list.js';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    localStorage.setItem('productCustomizations', JSON.stringify(editedProducts));
    
    // Also save product-customizations.json for git commit
    const customizationsJson = JSON.stringify({
      version: "1.0",
      lastUpdated: new Date().toISOString(),
      customizations: editedProducts
    }, null, 2);
    const jsonBlob = new Blob([customizationsJson], { type: 'application/json' });
    const jsonUrl = URL.createObjectURL(jsonBlob);
    const jsonLink = document.createElement('a');
    jsonLink.href = jsonUrl;
    jsonLink.download = 'product-customizations.json';
    document.body.appendChild(jsonLink);
    jsonLink.click();
    document.body.removeChild(jsonLink);
    URL.revokeObjectURL(jsonUrl);
    
    alert('Generated:\n- final-product-list.js (use in app)\n- product-customizations.json (commit to git)');
  };

  const hasCustomizations = (productId: string) => {
    return editedProducts[productId] && Object.keys(editedProducts[productId]).length > 0;
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-white shadow-sm border-b sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 py-4">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Product Admin Panel</h1>
              <p className="text-sm text-gray-600 mt-1">Manage products, images, descriptions, and pricing</p>
            </div>
            <div className="flex gap-3">
              <button onClick={() => setShowPreview(!showPreview)} className={`px-4 py-2 rounded-lg font-medium ${showPreview ? 'bg-gray-200 text-gray-700' : 'bg-blue-600 text-white'}`}>
                {showPreview ? '👁️ Hide Preview' : '👁️ Show Preview'}
              </button>
              <button onClick={saveFinalProducts} className="px-4 py-2 bg-green-600 text-white rounded-lg font-medium">
                💾 Generate final-product-list.js
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 py-6">
        <div className="grid grid-cols-12 gap-6">
          <div className="col-span-12 lg:col-span-4">
            <div className="bg-white rounded-lg shadow-sm border">
              <div className="p-4 border-b bg-gray-50">
                <h2 className="text-lg font-semibold">Products ({sourceProducts.length})</h2>
              </div>
              <div className="overflow-y-auto" style={{ maxHeight: '70vh' }}>
                {sourceProducts.map((product) => (
                  <button key={product.id} onClick={() => setSelectedProduct(product)} className={`w-full text-left p-4 border-b hover:bg-gray-50 ${selectedProduct?.id === product.id ? 'bg-blue-50 border-l-4 border-l-blue-600' : ''}`}>
                    <div className="flex items-start gap-3">
                      <div className="w-16 h-16 flex-shrink-0 bg-gray-100 rounded overflow-hidden">
                        {product.images?.[0] ? (
                          <img src={product.images[0].src} alt={product.name} className="w-full h-full object-cover" />
                        ) : (
                          <div className="w-full h-full flex items-center justify-center text-gray-400 text-xs">No image</div>
                        )}
                      </div>
                      <div className="flex-1">
                        <h3 className="font-semibold truncate">{product.name}</h3>
                        <p className="text-sm text-gray-600">ID: {product.id}</p>
                        <p className="text-green-600 font-bold">${product.basePrice}</p>
                        {hasCustomizations(product.id) && (
                          <span className="inline-block mt-1 px-2 py-0.5 bg-green-100 text-green-800 text-xs rounded">Modified</span>
                        )}
                      </div>
                    </div>
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="col-span-12 lg:col-span-8">
            <div className="bg-white rounded-lg shadow-sm border">
              <div className="p-4 border-b bg-gray-50">
                <h2 className="text-lg font-semibold">{selectedProduct ? `Edit: ${selectedProduct.name}` : 'Select a Product'}</h2>
              </div>
              <div className="p-6 overflow-y-auto" style={{ maxHeight: '70vh' }}>
                {selectedProduct ? (
                  <div className="space-y-6">
                    <div>
                      <label className="block text-sm font-medium mb-2">Display Name</label>
                      <input type="text" value={getProductData(selectedProduct.id).name} onChange={(e) => updateProduct(selectedProduct.id, { name: e.target.value })} className="w-full px-3 py-2 border rounded-lg" />
                    </div>
                    <div>
                      <label className="block text-sm font-medium mb-2">Short Description</label>
                      <input type="text" value={getProductData(selectedProduct.id).description || ''} onChange={(e) => updateProduct(selectedProduct.id, { description: e.target.value })} className="w-full px-3 py-2 border rounded-lg" />
                    </div>
                    <div>
                      <label className="block text-sm font-medium mb-2">Long Description</label>
                      <textarea rows={4} value={getProductData(selectedProduct.id).longDescription || ''} onChange={(e) => updateProduct(selectedProduct.id, { longDescription: e.target.value })} className="w-full px-3 py-2 border rounded-lg" />
                    </div>
                    <div>
                      <label className="block text-sm font-medium mb-2">Base Price</label>
                      <input type="number" step="0.01" value={getProductData(selectedProduct.id).basePrice} onChange={(e) => updateProduct(selectedProduct.id, { basePrice: parseFloat(e.target.value) })} className="w-full px-3 py-2 border rounded-lg" />
                    </div>
                    <div>
                      <label className="flex items-center space-x-2">
                        <input type="checkbox" checked={getProductData(selectedProduct.id).featured || false} onChange={(e) => updateProduct(selectedProduct.id, { featured: e.target.checked })} className="w-4 h-4" />
                        <span className="text-sm font-medium">Show as featured product</span>
                      </label>
                    </div>
                    <div className="border-t pt-6">
                      <h3 className="text-lg font-semibold mb-4">📸 Product Images</h3>
                      <ImageUpload productId={selectedProduct.id} images={getProductData(selectedProduct.id).images || []} onImagesUpdated={(images) => handleImagesUpdated(selectedProduct.id, images)} />
                    </div>
                    <div className="border-t pt-6">
                      <button onClick={() => { const newEditedProducts = { ...editedProducts }; delete newEditedProducts[selectedProduct.id]; setEditedProducts(newEditedProducts); }} className="w-full px-4 py-2 bg-red-50 text-red-600 rounded-lg">Reset to Original</button>
                    </div>
                  </div>
                ) : (
                  <div className="text-center py-12"><p className="text-gray-500">Select a product from the list to edit</p></div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
