// ProductAdmin.jsx - Updated with Categories Support
import React, { useState, useEffect } from 'react';
import { compiledProducts } from '../data/compiled-products';
import { PRODUCT_CATEGORIES } from '../utils/categoriesConfig';
import { Download, Save, Upload, Edit, Eye, EyeOff } from 'lucide-react';
import { Container, Row, Col, Alert, Button, Form, Card } from 'react-bootstrap';
import ProductGallery2 from '../components/product/ProductGallery2';

const ProductAdmin = () => {
  const [sourceProducts] = useState(compiledProducts); // Read-only source
  const [editedProducts, setEditedProducts] = useState({});
  const [selectedProduct, setSelectedProduct] = useState(null);
  const [showPreview, setShowPreview] = useState(false);

  // Load existing customizations
  useEffect(() => {
    const loadExistingCustomizations = async () => {
      try {
        const saved = localStorage.getItem('productCustomizations');
        if (saved) {
          setEditedProducts(JSON.parse(saved));
        }
      } catch (e) {
        console.warn('No existing customizations found');
      }
    };
    loadExistingCustomizations();
  }, []);

  // Get product data (source + customizations)
  const getProductData = (productId) => {
    const sourceProduct = sourceProducts.find(p => p.id === productId);
    const customizations = editedProducts[productId] || {};
    return { ...sourceProduct, ...customizations };
  };

  // Update product customization
  const updateProduct = (productId, updates) => {
    setEditedProducts(prev => ({
      ...prev,
      [productId]: { ...prev[productId], ...updates }
    }));
  };

  // Handle category selection
  const handleCategoryChange = (productId, categoryValue, isChecked) => {
    const currentData = getProductData(productId);
    const currentCategories = currentData.categories || [];
    
    let newCategories;
    if (isChecked) {
      // Add category if not already present
      newCategories = currentCategories.includes(categoryValue) 
        ? currentCategories 
        : [...currentCategories, categoryValue];
    } else {
      // Remove category
      newCategories = currentCategories.filter(cat => cat !== categoryValue);
    }
    
    updateProduct(productId, { categories: newCategories });
  };

  // Handle images update
  const handleImagesUpdated = (productId, updatedImages) => {
    console.log('Images updated for product:', productId, updatedImages);
    
    // Update the product with new images array
    updateProduct(productId, {
      images: updatedImages
    });
  };

  // Generate final-product-list.js content
  const generateFinalProducts = () => {
    const finalProducts = sourceProducts.map(product => {
      const customizations = editedProducts[product.id] || {};
      
      // Merge source data with customizations
      const finalProduct = { ...product };
      
      // Apply customizations
      if (customizations.name) finalProduct.name = customizations.name;
      if (customizations.description) finalProduct.description = customizations.description;
      if (customizations.longDescription) finalProduct.longDescription = customizations.longDescription;
      if (customizations.basePrice) finalProduct.basePrice = customizations.basePrice;
      if (customizations.featured !== undefined) finalProduct.featured = customizations.featured;
      
      // Apply categories
      if (customizations.categories) finalProduct.categories = customizations.categories;
      
      // Apply Cockpit3D option mappings
      if (customizations.cockpit3dOptions) {
        finalProduct.cockpit3dOptions = customizations.cockpit3dOptions;
      }
      
      // Handle size pricing overrides
      if (customizations.sizes) {
        finalProduct.sizes = finalProduct.sizes?.map((size, index) => ({
          ...size,
          ...(customizations.sizes[index] || {})
        }));
      }
      
      return finalProduct;
    });

    // Generate the JavaScript file content for final-product-list.js
    return `// final-product-list.js - Generated by Admin Panel
// DO NOT EDIT MANUALLY - Generated from compiled-products.js + customizations
// Generated: ${new Date().toISOString()}
export const finalProductList = ${JSON.stringify(finalProducts, null, 2)};
export const customizationInfo = {
  generated_at: "${new Date().toISOString()}",
  source_products: ${sourceProducts.length},
  customized_products: ${Object.keys(editedProducts).length},
  total_products: ${finalProducts.length},
  has_custom_images: ${finalProducts.some(p => p.images?.some(img => img.src.includes('/uploads/')))},
  admin_customized: true
};

export default finalProductList;
`;
  };

  // Save final-product-list.js file
  const saveFinalProducts = () => {
    const content = generateFinalProducts();
    const blob = new Blob([content], { type: 'application/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'final-product-list.js';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    // Also save to localStorage
    localStorage.setItem('productCustomizations', JSON.stringify(editedProducts));
    
    alert('final-product-list.js generated! Replace the file in your src/data/ folder.');
  };

  const hasCustomizations = (productId) => {
    return editedProducts[productId] && Object.keys(editedProducts[productId]).length > 0;
  };

  // Get categories that are not 'all'
  const availableCategories = PRODUCT_CATEGORIES.filter(cat => cat.value !== 'all');

  return (
    <Container fluid className="mt-3">
      {/* Header */}
      <Row className="mb-4">
        <Col>
          <h1 className="display-4">Product Admin Panel</h1>
        </Col>
        <Col xs="auto">
          <Button
            variant={showPreview ? "outline-primary" : "primary"}
            onClick={() => setShowPreview(!showPreview)}
            className="me-2"
          >
            {showPreview ? <EyeOff size={20} /> : <Eye size={20} />}
            {showPreview ? ' Hide Preview' : ' Show Preview'}
          </Button>
          <Button
            variant="success"
            onClick={saveFinalProducts}
          >
            <Download size={20} />
            {' Generate final-product-list.js'}
          </Button>
        </Col>
      </Row>

      <Row>
        {/* Product List */}
        <Col md={4}>
          <Card>
            <Card.Header>
              <h5 className="mb-0">Products ({sourceProducts.length})</h5>
            </Card.Header>
            <Card.Body className="p-0" style={{maxHeight: '600px', overflowY: 'auto'}}>
              {sourceProducts.map(product => (
                <div
                  key={product.id}
                  className={`p-3 border-bottom ${
                    selectedProduct?.id === product.id ? 
                    'bg-primary bg-opacity-10 border-primary' : ''
                  }`}
                  style={{cursor: 'pointer'}}
                  onClick={() => setSelectedProduct(product)}
                >
                  <div className="d-flex justify-content-between align-items-start">
                    <div>
                      <h6 className="mb-1">{product.name}</h6>
                      <small className="text-muted">ID: {product.id} • SKU: {product.sku}</small>
                      <div className="text-success fw-bold">${product.basePrice}</div>
                      {hasCustomizations(product.id) && (
                        <span className="badge bg-success mt-1">Modified</span>
                      )}
                      {/* Show assigned categories */}
                      {getProductData(product.id).categories && getProductData(product.id).categories.length > 0 && (
                        <div className="mt-1">
                          {getProductData(product.id).categories.map(catValue => {
                            const category = PRODUCT_CATEGORIES.find(c => c.value === catValue);
                            return (
                              <span key={catValue} className="badge bg-secondary me-1" style={{fontSize: '0.7rem'}}>
                                {category?.label || catValue}
                              </span>
                            );
                          })}
                        </div>
                      )}
                    </div>
                    <Edit size={16} className="text-muted" />
                  </div>
                </div>
              ))}
            </Card.Body>
          </Card>
        </Col>

        {/* Edit Panel */}
        <Col md={4}>
          <Card>
            <Card.Header>
              <h5 className="mb-0">
                {selectedProduct ? `Edit: ${selectedProduct.name}` : 'Select a Product'}
              </h5>
            </Card.Header>
            <Card.Body>
              {selectedProduct ? (
                <Form>
                  {/* Basic Info */}
                  <Form.Group className="mb-3">
                    <Form.Label>Display Name</Form.Label>
                    <Form.Control
                      type="text"
                      value={getProductData(selectedProduct.id).name}
                      onChange={(e) => updateProduct(selectedProduct.id, { name: e.target.value })}
                    />
                  </Form.Group>

                  <Form.Group className="mb-3">
                    <Form.Label>Short Description</Form.Label>
                    <Form.Control
                      type="text"
                      value={getProductData(selectedProduct.id).description || ''}
                      onChange={(e) => updateProduct(selectedProduct.id, { description: e.target.value })}
                    />
                  </Form.Group>

                  <Form.Group className="mb-3">
                    <Form.Label>Long Description</Form.Label>
                    <Form.Control
                      as="textarea"
                      rows={3}
                      value={getProductData(selectedProduct.id).longDescription || ''}
                      onChange={(e) => updateProduct(selectedProduct.id, { longDescription: e.target.value })}
                      placeholder="Detailed product description..."
                    />
                  </Form.Group>

                  <Form.Group className="mb-3">
                    <Form.Label>Base Price Override</Form.Label>
                    <Form.Control
                      type="number"
                      step="0.01"
                      value={getProductData(selectedProduct.id).basePrice}
                      onChange={(e) => updateProduct(selectedProduct.id, { basePrice: parseFloat(e.target.value) })}
                    />
                  </Form.Group>

                  <Form.Group className="mb-3">
                    <Form.Check
                      type="checkbox"
                      label="Show as featured product"
                      checked={getProductData(selectedProduct.id).featured || false}
                      onChange={(e) => updateProduct(selectedProduct.id, { featured: e.target.checked })}
                    />
                  </Form.Group>

                  {/* Product Image Gallery */}
                  <div className="border-top pt-3 mt-3">
                    <h6 className="text-primary mb-3">Product Images</h6>
                    
                    {/* Current Images Display */}
                    {getProductData(selectedProduct.id).images && getProductData(selectedProduct.id).images.length > 0 && (
                      <div className="mb-3">
                        <ProductGallery2 images={getProductData(selectedProduct.id).images} />
                      </div>
                    )}
                    
                    {/* Simple Upload Interface */}
                    <Form.Group className="mb-3">
                      <Form.Label>Add More Images</Form.Label>
                      <input
                        type="file"
                        accept="image/*"
                        multiple
                        className="form-control"
                        onChange={(e) => {
                          const files = Array.from(e.target.files);
                          // Process files here - will add this functionality
                          console.log('Files selected:', files);
                        }}
                      />
                      <Form.Text className="text-muted">
                        Select multiple images to add to this product gallery. First image will be set as main if no main image exists.
                      </Form.Text>
                    </Form.Group>
                  </div>
                  <div className="border-top pt-3 mt-3">
                    <h6 className="text-primary mb-3">Product Categories</h6>
                    <Form.Group className="mb-3">
                      <Form.Label>Select categories for this product:</Form.Label>
                      <div className="mt-2" style={{maxHeight: '200px', overflowY: 'auto'}}>
                        {availableCategories.map(category => {
                          const currentCategories = getProductData(selectedProduct.id).categories || [];
                          const isChecked = currentCategories.includes(category.value);
                          const IconComponent = category.icon;
                          
                          return (
                            <div key={category.value} className="form-check mb-2">
                              <input
                                className="form-check-input"
                                type="checkbox"
                                id={`category-${category.value}`}
                                checked={isChecked}
                                onChange={(e) => handleCategoryChange(selectedProduct.id, category.value, e.target.checked)}
                              />
                              <label className="form-check-label d-flex align-items-center" htmlFor={`category-${category.value}`}>
                                {IconComponent && <IconComponent size={16} className="me-2" />}
                                <span>{category.label}</span>
                                {category.description && (
                                  <small className="text-muted ms-2">- {category.description}</small>
                                )}
                              </label>
                            </div>
                          );
                        })}
                      </div>
                      <Form.Text className="text-muted">
                        Categories help organize products and improve customer browsing experience.
                      </Form.Text>
                    </Form.Group>
                  </div>

                  {/* Cockpit3D Option Mappings */}
                  <div className="border-top pt-3 mt-3">
                    <h6 className="text-primary mb-3">Cockpit3D Option Mappings</h6>
                    
                    {/* Size Option Mapping */}
                    <Form.Group className="mb-3">
                      <Form.Label>Size Option ID</Form.Label>
                      <Form.Control
                        type="text"
                        placeholder="e.g., 241"
                        value={getProductData(selectedProduct.id).cockpit3dOptions?.sizeOptionId || ''}
                        onChange={(e) => updateProduct(selectedProduct.id, { 
                          cockpit3dOptions: { 
                            ...getProductData(selectedProduct.id).cockpit3dOptions,
                            sizeOptionId: e.target.value 
                          }
                        })}
                      />
                      <Form.Text className="text-muted">
                        Cockpit3D option ID for sizes (from raw catalog)
                      </Form.Text>
                    </Form.Group>

                    {/* Face Option Mapping */}
                    <Form.Group className="mb-3">
                      <Form.Label>Face (Image) Option ID</Form.Label>
                      <Form.Control
                        type="text"
                        placeholder="e.g., 242"
                        value={getProductData(selectedProduct.id).cockpit3dOptions?.faceOptionId || ''}
                        onChange={(e) => updateProduct(selectedProduct.id, { 
                          cockpit3dOptions: { 
                            ...getProductData(selectedProduct.id).cockpit3dOptions,
                            faceOptionId: e.target.value 
                          }
                        })}
                      />
                      <Form.Text className="text-muted">
                        Cockpit3D option ID for image upload
                      </Form.Text>
                    </Form.Group>

                    {/* Light Base Option Mapping */}
                    <Form.Group className="mb-3">
                      <Form.Label>Light Base Option ID</Form.Label>
                      <Form.Control
                        type="text"
                        placeholder="e.g., 243"
                        value={getProductData(selectedProduct.id).cockpit3dOptions?.lightBaseOptionId || ''}
                        onChange={(e) => updateProduct(selectedProduct.id, { 
                          cockpit3dOptions: { 
                            ...getProductData(selectedProduct.id).cockpit3dOptions,
                            lightBaseOptionId: e.target.value 
                          }
                        })}
                      />
                      <Form.Text className="text-muted">
                        Cockpit3D option ID for light base accessories
                      </Form.Text>
                    </Form.Group>

                    {/* 2D Backdrop Option Mapping */}
                    <Form.Group className="mb-3">
                      <Form.Label>2D Backdrop Option ID</Form.Label>
                      <Form.Control
                        type="text"
                        placeholder="e.g., 244"
                        value={getProductData(selectedProduct.id).cockpit3dOptions?.twoDBackdropOptionId || ''}
                        onChange={(e) => updateProduct(selectedProduct.id, { 
                          cockpit3dOptions: { 
                            ...getProductData(selectedProduct.id).cockpit3dOptions,
                            twoDBackdropOptionId: e.target.value 
                          }
                        })}
                      />
                      <Form.Text className="text-muted">
                        Cockpit3D option ID for 2D backdrop options
                      </Form.Text>
                    </Form.Group>

                    {/* 3D Backdrop Option Mapping */}
                    <Form.Group className="mb-3">
                      <Form.Label>3D Backdrop Option ID</Form.Label>
                      <Form.Control
                        type="text"
                        placeholder="e.g., 245"
                        value={getProductData(selectedProduct.id).cockpit3dOptions?.threeDBackdropOptionId || ''}
                        onChange={(e) => updateProduct(selectedProduct.id, { 
                          cockpit3dOptions: { 
                            ...getProductData(selectedProduct.id).cockpit3dOptions,
                            threeDBackdropOptionId: e.target.value 
                          }
                        })}
                      />
                      <Form.Text className="text-muted">
                        Cockpit3D option ID for 3D backdrop options
                      </Form.Text>
                    </Form.Group>

                    {/* Service Queue Option Mapping */}
                    <Form.Group className="mb-3">
                      <Form.Label>Service Queue Option ID</Form.Label>
                      <Form.Control
                        type="text"
                        placeholder="e.g., 246"
                        value={getProductData(selectedProduct.id).cockpit3dOptions?.serviceQueueOptionId || ''}
                        onChange={(e) => updateProduct(selectedProduct.id, { 
                          cockpit3dOptions: { 
                            ...getProductData(selectedProduct.id).cockpit3dOptions,
                            serviceQueueOptionId: e.target.value 
                          }
                        })}
                      />
                      <Form.Text className="text-muted">
                        Cockpit3D option ID for service queue (Standard, Rush, Red Carpet, Jump Queue)
                      </Form.Text>
                    </Form.Group>

                    {/* Customer Text Option Mapping */}
                    <Form.Group className="mb-3">
                      <Form.Label>Customer Text Option ID</Form.Label>
                      <Form.Control
                        type="text"
                        placeholder="e.g., 906"
                        value={getProductData(selectedProduct.id).cockpit3dOptions?.customerTextOptionId || ''}
                        onChange={(e) => updateProduct(selectedProduct.id, { 
                          cockpit3dOptions: { 
                            ...getProductData(selectedProduct.id).cockpit3dOptions,
                            customerTextOptionId: e.target.value 
                          }
                        })}
                      />
                      <Form.Text className="text-muted">
                        Cockpit3D option ID for engraving text
                      </Form.Text>
                    </Form.Group>
                  </div>

                  <hr />
                  <Button
                    variant="outline-danger"
                    size="sm"
                    onClick={() => {
                      const newEditedProducts = { ...editedProducts };
                      delete newEditedProducts[selectedProduct.id];
                      setEditedProducts(newEditedProducts);
                    }}
                  >
                    Reset to Original
                  </Button>
                </Form>
              ) : (
                <div className="text-center text-muted py-5">
                  <p>Select a product from the list to edit</p>
                </div>
              )}
            </Card.Body>
          </Card>
        </Col>

        {/* Preview Panel */}
        {showPreview && (
          <Col md={4}>
            <Card>
              <Card.Header>
                <h5 className="mb-0">Generated File Preview</h5>
              </Card.Header>
              <Card.Body>
                <pre className="bg-light p-3 rounded" style={{fontSize: '0.75rem', overflowX: 'auto', maxHeight: '300px'}}>
                  {generateFinalProducts()}
                </pre>
              </Card.Body>
            </Card>

            <Row className="mt-3 g-2">
              <Col>
                <Card className="bg-primary bg-opacity-10">
                  <Card.Body className="text-center">
                    <div className="fw-bold text-primary">Source Products</div>
                    <div className="display-6 fw-bold text-primary">{sourceProducts.length}</div>
                  </Card.Body>
                </Card>
              </Col>
              <Col>
                <Card className="bg-success bg-opacity-10">
                  <Card.Body className="text-center">
                    <div className="fw-bold text-success">Customized</div>
                    <div className="display-6 fw-bold text-success">{Object.keys(editedProducts).length}</div>
                  </Card.Body>
                </Card>
              </Col>
              <Col>
                <Card className="bg-info bg-opacity-10">
                  <Card.Body className="text-center">
                    <div className="fw-bold text-info">Final Products</div>
                    <div className="display-6 fw-bold text-info">{sourceProducts.length}</div>
                  </Card.Body>
                </Card>
              </Col>
            </Row>
          </Col>
        )}
      </Row>
    </Container>
  );
};

export default ProductAdmin;